CREATE DATABASE bookstore;
USE bookstore;

CREATE TABLE PUBLISHER ( 
	CODE VARCHAR(4) NOT NULL,
	PUBLISHER_NAME VARCHAR(100) NOT NULL,
	PRIMARY KEY(CODE)
	);

CREATE TABLE BOOK (
	ISBN VARCHAR(15) NOT NULL,
	BOOK_NAME VARCHAR(100) NOT NULL,
	PUBISHER_CODE VARCHAR(4) NOT NULL,
	PRIMARY KEY(ISBN),
	FOREIGN KEY(PUBISHER_CODE) REFERENCES PUBLISHER(CODE) 
	ON DELETE CASCADE
);

CREATE TABLE CHAPTER (
	BOOK_ISBN VARCHAR(15) NOT NULL,
	CHAPTER_NUM INT NOT NULL,
	TITLE VARCHAR(100) NOT NULL,
	PRIMARY KEY(BOOK_ISBN,CHAPTER_NUM),
	FOREIGN KEY(BOOK_ISBN)  REFERENCES BOOK(ISBN) ON DELETE CASCADE
);